create database Grocery_Management;
-- Drop database Grocery_Management;

use Grocery_Management;

-- 1. Suppliers Table   ....
CREATE TABLE IF NOT EXISTS supplier ( 
    sup_id TINYINT PRIMARY KEY, 
    sup_name VARCHAR(255), 
    address TEXT 
);															

select * from supplier;

 -- 2. Categories Table  ...
CREATE TABLE IF NOT EXISTS categories ( 
    cat_id TINYINT PRIMARY KEY, 
    cat_name VARCHAR(255) 
); 

select * from categories;


-- 3. Employees Table   .... 
CREATE TABLE IF NOT EXISTS employees ( 
    emp_id TINYINT PRIMARY KEY, 
    emp_name VARCHAR(255), 
    hire_date VARCHAR(255) 
); 

select * from employees;


 -- 4. Customers Table    
CREATE TABLE IF NOT EXISTS customers ( 
    cust_id SMALLINT PRIMARY KEY, 
    cust_name VARCHAR(255), 
    address TEXT 
); 

select * from customers;


 -- 5. Products Table 
CREATE TABLE IF NOT EXISTS products ( 
    prod_id TINYINT PRIMARY KEY, 
    prod_name VARCHAR(255), 
    sup_id TINYINT, 
    cat_id TINYINT, 
    price DECIMAL(10,2), 
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
); 

select * from products;


 -- 6. Orders Table 
CREATE TABLE IF NOT EXISTS orders ( 
    ord_id SMALLINT PRIMARY KEY, 
    cust_id SMALLINT, 
    emp_id TINYINT, 
    order_date VARCHAR(255), 
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
);

select * from orders;



-- 7. Order_Details Table 
CREATE TABLE IF NOT EXISTS order_details ( 
ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY, 
ord_id SMALLINT, 
prod_id TINYINT, 
quantity TINYINT, 
each_price DECIMAL(10,2), 
total_price DECIMAL(10,2), 
FOREIGN KEY (ord_id) REFERENCES orders(ord_id) 
ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY (prod_id) REFERENCES products(prod_id) 
ON UPDATE CASCADE ON DELETE CASCADE 
); 

select * from order_details;


-- 1. Customer Insights 

-- ● How many unique customers have placed orders? 

select count(distinct cust_id) as total_customers
from orders;

-- Which customers have placed the highest number of orders?

select c.cust_name, count(c.cust_id) as total_orders
from customers c
join orders o on c.cust_id=o.cust_id
group by c.cust_id, c.cust_name
order by total_orders desc
limit 10;

-- ● What is the total and average purchase value per customer? 

select c.cust_name, sum(od.total_price) as Total_purchase ,
 avg(od.total_price) as average_purchase
from customers c
join orders o on c.cust_id=o.cust_id
join order_details od on o.ord_id=od.ord_id
group by c.cust_name
order by total_purchase;

-- ● Who are the top 5 customers by total purchase amount? 

select c.cust_name, sum(od.total_price) as Total_purchase
from customers c
join orders o on c.cust_id=o.cust_id
join order_details od on o.ord_id=od.ord_id
group by c.cust_name
order by total_purchase desc
limit 5;


-- 2. Product Performance 

-- ● How many products exist in each category? 

select ca.cat_name , count(p.prod_id) as Products_total
from categories ca
left join products p on ca.cat_id=p.cat_id
group by ca.cat_name;

-- ● What is the average price of products by category? 

select ca.cat_name , avg(p.price) as average_price
from categories ca
left join products p on ca.cat_id=p.cat_id
group by ca.cat_name;
 
-- ● Which products have the highest total sales volume (by quantity)? 

select p.prod_name, sum(od.quantity) as total_quantity
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_name
order by total_quantity desc;


-- ● What is the total revenue generated by each product? 

select p.prod_name , sum(od.total_price) as Total_revenue
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_name
order by Total_revenue desc;

-- ● How do product sales vary by category and supplier? 

select ca.cat_name, s.sup_name, sum(od.total_price) as Total_revenue
from order_details od
join products p on od.prod_id=p.prod_id
join categories ca on p.cat_id=ca.cat_id 
join supplier s on p.sup_id=s.sup_id
group by ca.cat_name,s.sup_name
order by Total_revenue desc;


-- 3. Sales and Order Trends 

-- ● How many orders have been placed in total? 

select count(ord_id) as total_order 
from  orders;

-- ● What is the average value per order? 

select avg(order_value) as avg_order
from (select ord_id, SUM(total_price) AS order_value
from order_details
Group by ord_id) orders;

-- ● On which dates were the most orders placed? 

select order_date, count(*) as most_order
from orders
group by order_date
order by most_order desc;

-- ● What are the monthly trends in order volume and revenue? 

select date_format(str_to_date(order_date, "%m/%d/%Y"), "%y-%m") as month,
count(distinct o.ord_id) as total_orders, sum(od.total_price) as Total_revenue
from orders o
join order_details od on o.ord_id= od.ord_id
group by month
order by month;	 

SELECT ord_id, order_date 
FROM orders
LIMIT 10;

-- ● How do order patterns vary across weekdays and weekends?

select case when dayofweek(str_to_date(order_date, "%Y-%m-%d")) in (1, 7) then "Weekend" else "Weekday"
end as day_type,

count(*) as total_orders,
sum(od.total_price) as total_revenue
from orders o
join order_details od on o.ord_id = od.ord_id
group by day_type
order by day_type;


-- 4. Supplier Contribution

-- ● How many suppliers are there in the database? 

select count(sup_id) as Total_suppliers
from supplier;

-- ● Which supplier provides the most products? 

select s.sup_name, count(prod_id) as product_count
from supplier s
join products p on s.sup_id=p.prod_id
group by s.sup_name
order by product_count Desc;

-- ● What is the average price of products from each supplier? 

select s.sup_name, avg(p.price) as average_price
from supplier s
join products p on s.sup_id=p.sup_id
group by s.sup_name;

-- ● Which suppliers contribute the most to total product sales (by revenue)? 

select s.sup_name, sum(od.total_price) as Total_revenue
from order_details od
join products p on od.prod_id=p.prod_id
join supplier s on p.sup_id=s.sup_id
group by s.sup_name
order by Total_revenue Desc;


-- 5. Employee Performance 

-- ● How many employees have processed orders? 

select count(distinct ord_id) as order_processed
from orders;

-- ● Which employees have handled the most orders? 

select e.emp_name, count(o.ord_id) as order_handled
from employees  e
join orders o on e.emp_id=o.emp_id
group by e.emp_name
order by order_handled desc;

-- ● What is the total sales value processed by each employee?

select e.emp_id ,e.emp_name, sum(od.total_price) as total_sales
from employees e
join orders o on e.emp_id=o.emp_id
join order_details od on o.ord_id=od.ord_id
group by e.emp_id
order by total_sales desc;


-- 6. Order Details Deep Dive

-- ● What is the relationship between quantity ordered and total price? 

select quantity , total_price
from order_details 
order by quantity asc;

-- ● What is the average quantity ordered per product? 

select p.prod_name , avg(od.quantity) as average_quantity 
from products p
join order_details od on p.prod_id=od.prod_id	
group by p.prod_name;

-- ● How does the unit price vary across products and orders? 

select p.prod_name, min(od.each_price) as min_price, 
max(od.each_price) as max_price 
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_name;










